from numpy import zeros, min


def function(sequence_1: str,
             sequence_2: str) \
        -> int:
    distances = zeros((len(sequence_1) + 1, len(sequence_2) + 1), dtype=int)

    for location in range(len(sequence_1) + 1):
        distances[location, 0] = location

    for location in range(len(sequence_2) + 1):
        distances[0, location] = location

    for location_1 in range(1, len(sequence_1) + 1):
        for location_2 in range(1, len(sequence_2) + 1):
            if sequence_1[location_1 - 1] == sequence_2[location_2 - 1]:
                distances[location_1, location_2] = distances[location_1 - 1, location_2 - 1]
            else:
                a = distances[location_1, location_2 - 1]
                b = distances[location_1 - 1, location_2]
                c = distances[location_1 - 1, location_2 - 1]
                distances[location_1, location_2] = min([a, b, c]) + 1

    return distances[len(sequence_1), len(sequence_2)]


if __name__ == '__main__':
    p_1 = ("EEENGFTSQDFLRVDPRISCFVWASDDLITWDACCYEHVEFPWIRCCLQSSSIVDFEVTALAEGDRRDLLPILSTWIMRWASINFCGFNSHYHAKPQFSNSKYAHKD"
           "SPMFAVKYMNPHMMQCVWCQCPCDTVMDCFACGWAEWGDKKCGMWFYLISLYKHSMKMFDGPVVGLMKNKMCSDAVVDGQLWMFVHRHGCVLTLFSLCHRTGIPHKG"
           "MGQDFSMIVWFPDPKDPGPHGRAIDGPTPYEMKHCTTPFYTQCFINHLLIPSVTAIDCDSQMYRVQEGKQHKMQKWNMKEAHLMMFKGAVWMNFPCYGDIVPFMYMS"
           "DEGHVSVDSVHHYMNDAMPDENTTVCFITAWRHPEKIDPWKYCHQTGPQEREEPLTERIWRMFFVNTSCRNEDDMEAWGKLDECNCHYMRTSPNSIDKAWEVRNCGN"
           "GNGEQDCEILPTSFMYTQECDYESLKHNQSWPTWPETFRYCNIIEISSKHAGQEVTSWNWKRSVYCRKAPGTYDDWQDCTCAPFIYAAMGFTWNAKIMKYEHEMDFQ"
           "EEYRSPWGCHLCSGEFEREDVQERESIHTPLDVEGKNGRYTMCWTYEKGREWNKPDYTHDCWQGLPICPQRKPEFAWAGIECTNSLIYAFFYPFYEAFQGHVIMWDW"
           "QGSKYNMANHTNRSNQHVIMGARTAQDKCGGWHTMDKKAANADRERIVTMRMCCVQKAPQISDLVQIQCHTMFYPECGQLNRWTKWVTRPWINNRWCKATKFIKEKK"
           "FIQHSKLPFLMAYTRMLEKTFRIENVMGDIDNDPTSRFFRCELCKFKEVDEHSRQYYKEERAMFINDSYWDPACPNTVVLYRSIDWAHCTQLKFPLQEKRCFDMFDD"
           "YQRCMKGPFNNETAPINSCEKTIHDFRYGNLWTVIPRMCTCDVPLDCPRTGLAHTIMVKLCIMRDMEQENVCWPSCQKEADADCQPFHNFCQSHSDFTTRNTIDSKG"
           "LAVMAICYPTFWWPCITCPWPNWCSTVGDNRVRDIHLKPQNWEWKRTWFCEVTAPNYVGSCEVRQIDSCKKYGWDEWLYGNVCMINDWRPAKFNAPTGCELYNHFDY"
           "DMQHQVQMHYEWNPKSGQQCQYMPVPMYITMWSCHSNLVVQTVHMPLNVLRHRRQCKMFQPCFSWFARHLDQCGWVEVCYRSRQKDMEQVEYSQYIGSQLLQRTWWS"
           "CAKQGIGFGLYNAAPCDPNMIYQIKSSWKWIDQMVITGFEEPLSGHHVSFLFVGQIGCESVAITKEKASYEEHYWIWERCYSIDPWCAVVVNDLCTFCEDRCNCWDE"
           "WYGYKFKWMRQSFMEWMHDYGHFQMGLRTHLYLDYHAMRFIQHYIHAASLAKWRHPARTTLPLDCYINQMHYVLHYRMIAIKHDAMRDFWWPDYICGFRWNNINQYS"
           "PSTVNHKVFNWIGQAYGRICDEPNDHDMDARWVWGFGYLFYYKIEHQEIMENVMNMRRRHPKTMPFAMWNNAKFPKYWQTREKYHDRILAPYNDMPLMMPIEFYVIK"
           "QSCPAWRYDRHSRQHTIRYNGKEHWDYWDYEKSWDFGYIMVMNRFYCQNVPPTIGIYMMSVWDAIENRARDNPYPGAAQQNCCYKNVPNTQEQRQTIHAASIPNCIH"
           "SQHVMQFGMRLDKPCNRVFAMRHAVTNVCWCCFRNSSSLRRGHCQNIWPLCQGVEYPPRYQMELCHQCTGSGLPMQFFFECCQKKQPGIWHQKIMIWWLEREAWGAR"
           "WMPRQWHDSVSVHEHEYNFFQSKFKCAWSAKKWMDCIISEWMCHKSGQVIMKQLWPKCHMNNACLSHFTVCWDRQKYQHRPDVGVAQWKFIMEQFEGDQDNDYMNMS"
           "RDFVHFYSHHNRANIFLAYSWQQVYAHHHYESYLYKDTHHVCDSSKNDRVAKWKPMLVQFNTIPMCWQKRMHMHSKVPWHVDQQDCNRQSDFIHNTLCPTLLWNHDD"
           "CFWRMGWREWVNHMHCANTHTNHNLWAFLYCRWGVFPMAGIQVRHHNVQMSQDARHMVGCPDFSHPRWRDKHGQVPCDHFGNDGTKGFDNWYGAITMYLIFCQIWCG"
           "DHSQPTAQKTIDQLIILHTKAFMESMGYSVSPFAGRMWPKKFENVGPGCIPYQTWDVDFTCGELSTPDMCGNTHWNIMMHHFAMFQTSAFFNGKSPPLCVVGYSQGK"
           "DHLQWWIANFLTNEYFDCNKQITECSKFMCYSIYMMQWRRIQSKYFHDNTMDRQEDRHGFLENHDSRPFANFRTCQKIKMVCFENNIMTVYDDFPSDKVEDGLMFMA"
           "RIDDHTPMSMDRDKGKKKVPAHVVQTRCSQKYHIYWDMYCTRTCITVWDFSDTMSPMSKKVAYTSHCIEAPCSTYEQVTLWYVTEGTCEAQGFEFMEKNNVVQRNPM"
           "CDQCFIPAWMAERSATLIVVQKAQRILPAQAVHMQRERRNEYCFCPLNILQACYMNPLKSSQCLKCVHLPIPEIELMMAIMESWWETNRQAKTHCMGGKNPTGFGAL"
           "MQIVFSERQEDLLMGQMTWMCFKGTRAKWMNAGPMPNDWQQEIQREGKEHWYREQMYCHAKYPLIHHMEFYDLAFMYYCAVPAPRRCACDTNQYVPGSEYWVIFLHW"
           "IVYFHNMIFDWQERCVPIEPVCNHLMCPAWEGDILHINSPRLMAVVMMIHCMTEHAMRSYQEAFRHCMWQQPAPWCSLIDKGNEAQATIKSSMIKKWDYFMVWGWTK"
           "DMFGMQSQQLDFFFCTEKCSRWMHGWQGGEVCAMANAKQTNSRAHAFEEWRGSDIMEIYRRPGEFHQPLLPSHESIHNLMMQCQGHSCCHTPIYDSMGNPKARMFEK"
           "TPCGQASPNWRQWQGHNWDVFKDGTDMWLPGWPHIRKVMAFTGTRTMLDGRNIEPWKRIAKELYINELCVDQGEMYFEKTHDNWPPMPIPIPCSINNGTFKQKASMA"
           "TYMDKWSIRTAISCKQQIACLHSQSSPAKMWQFWWYDMAGDTEFMCQHGPCDINFTDDDFWQQQQAQYMGMCCHRCELISSVQEWGCYPMDCIWTDACQFSWPSFNL"
           "EQDNFQHKFGNQKHYNFYWRLRDPFDEMSGEFHQKVPLHFFFMDNLAWAQRCSDYNMKQGMSRFLAWTRGEGGCFGCRGCDEAPCFNWIWLMTGMMHATWKKQVTDN"
           "WRLFWRAMTDYKELVFGCHQWNMSRRDKIAKKCGYVGLCIRRRCTAYDSWGTRHWYPEKIAHCQHFTANAPAVWMKSSKIHGMGDQMVNWQMMKPQHSEQLMWYKFV"
           "DSHRIWCNEFFVHQEGGQDHGANCATHTWGYNVDTLDHADLVNKEMLRWPRPMLGNICMSGNMSERHVEKHHCPKQFMHQRRAFGKNWPKGYADDNFHGRGVHISFY"
           "EKIGFHIAIFSTPQPTGFQKISEAVCSLKVIKFHHNYPHCSEKRLERCYSGIGNREIIVGNFLTEWAVKYTHTIAFPYTTEECCCASKCDFHSGSQPTFWMIHLHGP"
           "AMSDGQVVYNKTCCEPHEEEQMWLIWVLALGAYTSGYFMACVNRRGLVHMTNVHVQDHIRGRQSVTCPFTNINTHELPVSQQDNFQAGWRARHIGQAWDGQWQLIHA"
           "VYGCLRIEQEHMAEEYPAKWPKRMLATYKGFFQAKHQCRFKFTHTTGMKKYDEHLVQYHARKENYHNQETQAYMEARAQKCSRSYREDNLAHRRERELVCMYWLYGR"
           "DTWETIVEHQFVHIFWAGSVDCLTCWAWVQTMVIIPCIWSEANEPMTLAMVIMWFHFTDIRWPANSFMYEARYECEFWTKDYGCDFVQYVFDTTTDNPNWYIEYTHP"
           "QFIWRIWCIMYIWVEHGFRPESEYFVMQWEDMWWNQWLWLPETKDKSIYMLNCPVFNRQGPISSKMEEIKQMRCIQVEGHANSCESIMCVMIRQQEHMMSKKANDWS"
           "KLICRDMFSMFKSCHYEEKKHDFFFSEEEEPNKAQFLWPQNRMD")
    p_2 = ("EEENGFTSQDFLRVDRISPTWVWPFFACCYEHVEFPWIRCCLQVHNMYSSIVDFEVTVWDLMLAEGDRSRILSTWIMRWASFSGGFNSHYHAKPQFSNSKYAHKDSP"
           "AQVCAVYHVRHAAVTQGSCRVMMMQCVWCVMDCFACGWAMYLISLYKDGPVVGLMKNKGCACSDAVVQGQLWMFVHRHGCLRGQLTLFSLCTGIPWKGKVYAYWNGM"
           "DFSMIVWNNLDPGPGPIGRAIDGPTPYEMKHFTQPFCTQCFINHLLIPVVTAIDCVSQMYRVQEGKQYLKGWHDQWLPVYKWNNHNVTSTCKEAHLVGVNHGVKDQF"
           "KGAVWCYPMEVQEMYFHVSVDSSDAMPDSNTRVHVCFITAWRHSEKIDPFPQRREEPLTERIWRMFYVNMVQHSFKAMKKCVIHGAWGKEHQTWGPYSIDKAWHVRN"
           "GEQDCGYILPTSYESLKHNRSWVTRPETKDGCWQEVYSCWNWKRFVYCPKAPGTYDDWQDCFHPSWEFFEAPFSYADMGFFVGLWNAKILKILVNWEGYEEYRSPWG"
           "RTHLCSGEFEREDVQERESPKHTPLDVEGHIGRAKNGCYTMCWTNKPDYTHDCWQGLPICPQERYFAQRPEFAWAGIYCTNSLIYAFFYLYEAFQGHVIMWDWQGSY"
           "NMANHRNANRMGARTAQDKCGGWHTMDKKYLANADRRYKMLMRITMRMCCVQKAPQISWPEFMYFANLTGVQQRTMFVPEQTPLNRWTPGVDINCQYSIKWYVSTMT"
           "KLEKKYIQHSKLPFLMAYTRMLEWVGQEFTSGTKVFIWMVQAPYADCRDIDPFHRFFRCELMSKFSQYYKEPYLSYWDPACPNTVVLYRSIDWAHCPLQDDKGPINS"
           "CCKTIHDFRYGNLWLVIDCPRTGLAHTIMVKLIIMRDMEQENVCWPDADCQPFHNFCPSHSDFTTRNAIDSKGLDYWSLWFTVMATFWWLCITCPPNWCSTVGWNRV"
           "RDIHLKPINWEWWFCEVTAPNIKEWLIKREMNHIRDWRPAKFNAPTGSLALYLAMWVAWRFHYEQYMPVPMITTTCNGSCHSTLVVQTVHMPELRHRYYVKEQFLFA"
           "RHLDQMEYGWVEVCYNSRQYSSYPGSQLLNGTWWGCAVDTQELGIFHFPCDPKRKLTIMIYQTKSSWKWMVRKSFFEFQMVITGFEEPQGMSNKGLESFVGQIGIEC"
           "IDINSVAITKEKASMCIPVQNEWGEHYWIWERCYSIDPWFASMNVVNDLTCVNVQRCNCWDEHYIYIYEYKFKWGRQHFMEWMHDYGAEVWHFGNGLRTHLYLDYHA"
           "MRIWNRNYGQMGQGYIHATSLAKWMDPTTREAGQLPLDCTINQMHVLHYRMIAIKHCGAMRDFWWPFYSCGFRWNEINQYSPSTVNHKVFNWIGDEPNDHVCYVDSG"
           "WSQRPGPSWYLFYYKIEHQEIMENEMNMERARAMWNNAAFPKYWRFLVSKYHRPDRILAPYMWEMAWCVDDMPLYLQIEFYVIGWTPTAAHYQSCTAWRYDRLSRQH"
           "TIRYNGYWWWYTLSHWDYWDYEKSWDIDMFAGYIDMNRFYMCMIVQVPPEDGIYMMSVWDAIEARDNPPGAAQQNCCYKNVPNTQEQRQKIHAASIPNCIHSQHVMQ"
           "FGMRLDKPCFPNASSEQVFAMRHAVTNVCWCFFLWGGKRDSSSLRRQHCQNGVDMKRRFTFYQMMDQQESFFMCCQVGEMTEPKQPGINTQKPEYSMIWWLEGCMKC"
           "MRDEALGARRDSVSVTHTFQLNEQWCCKFKCAWSAKKWNDGIISEWMRHKPGWPKCHMNNICLSHVCWDRQKYVRHRPDEGTAQWKFIMEQESEEGDLDNDYMNMSR"
           "DFVHFYSHHNRANIFLAYSWQQAYAHHHYEPYLPFMGFTSDTHHVSKNDRVAKWKPMRVQFWDWFCYDPMCWQKTGLHYCPYMHHSKVPWHVWQQDENRQSDFIAEC"
           "MPSVFNTLCPTLLWNHDDWRQGYSYFMHCAATHTQHNLWAFLYCRWGVFPMNGIEKVRHSWMHISNQADAYHHMMPPMHNYLTQCPDFSAMMRSYTHGQVPEQYLFS"
           "YFDHFNNDGTKGFDNCTMYLIWPQCKERMSQPCAQETIDNDEMIQYDYGYSVSIFYVEPTVLRGRMWPKKDENYTMLLQGPGCIHYPPNAQFEWLGEPDMCGNTHDM"
           "MHHFAMFRADTSAGFNGKSWPLCVVGYSQGKDHLANFLDGDIKLKQIYNMLYTFCGCSKFMYRTSIYKQNHCNPDMMQWRRRQSTYFCDQTMDRKAWWEDRMGENEN"
           "HHMRPFANFRTCQLIKMVCYENNIMTVIRESNEYWVDGLMFHARIDDHTPMSMKKKVPAYWDQQPRWIWVQTRCMAGVHWPTKYDIYTRTCHTCNWDFSLKVLTCTP"
           "YSRVYTSHCIEAPCSTYEQVTWWYVLEGHYEAQGFEFMEKNKKYHNIGCDQDFIPAYFKDAERVQKAQREGCAGMQNEYCFCPLLGDIPQACYMNPLKSSQHLAVYC"
           "SFHHLPPGHEIMAIMESWETNRQVFFKTHCTGGKNPTGFQALMQIVFKVSELHSAGQEDRKKGQMTWMCFKGTKWMNAGPMPNDWQQEIGDEGKEHWYREQMPLIHH"
           "MEFYDLAFMYACAVMRLCYACDTNGYVPGGWGIKGKSEYWVIFLHWIPYFHNMIFDWQERCIPIFTWEYHSQIAVCNHLMCPGCWPRLMAVVMMIHSYQEAFRKCMW"
           "QLTSDYPAPWHIGYLFLIDKGNEAQATIKGSMIKKWDYFMVWGWTKDMFGMQSQTLDFFICPEGWQGGGVCAMRNSVTEFTDEMWFYSDIMEIRILRRPGEFHQPLL"
           "PSHEFWDNEHNWMIMNMMRCQGHSSKVPSIQCHTPIKDSMGNPKWSMYTYKLRMFEFRWCHAPCCQASPWRQWQGHNWHNFKDGTDMWLAQGIGAPHERKVSAFTGT"
           "RTMLQGRNIEPQAKELYLNEHCIDQGEMYFEMPIPIPCSINNKTFTVNVYERVIQHEQKWSIDKQFDILAISDKQQIACLHFPSPAKMWQIWWYTCCEVHMAGDTEM"
           "LGMWTMCHGPCDINFTDDDQAQCCHRCELISSVQEWGCYPMDCIWTDAEMGNAWKQFFWPSFNLEVDNCQHKFGNQKHCMLCEHMNFYWQDHDHNMELCDPFDEFHQ"
           "SRIWAQHVPLHFFFMDAFKPCMCHLAWAQRCSDYNMKVGMSRIAILIEVCWEIGPGCDYKDWDRAPCFNWIGMMHATWKKQVTDNWRQAFWFHFWQAMTDYKETVFG"
           "CHQWNMSRRDKIAKKCGYVGLCIRRRCTAYNDVRWFTRHWYPEAEWDKHVTLHVATAHCQHFTKFAVWMKSSKIHGMGDQMFKKTFQMQMFVDSHRIWCNLFFDHGE"
           "GGQKGINIPFVDHGANCATHTHHEGYNVDTLRHADRQYSITIVNFQWIREMYGDPRPMMGNICMSGNMSERHYSDRPRTEKHCPKQFMHQNRAMMKNWPKGCTCYAF"
           "HGRGKIGFHIPIFSTPQPTGFQKISEAVWSLKVIKHNPHRLFTWDWWNREIIVTHFPYTTEECCCASKCDFHWMIWHGPAYNKTCCEDHEEEQMRLHNMQWVLAFDA"
           "YTSGYFMACVNRPYLFTLNAPDRHMTNVHQDHIRVTCPFTNIKNPVSQQQNFQAGWRARSYLLSWGCWQGCLRIEEHMTEEYPAKWPLATYDQCRFKFERLAIELQE"
           "HTTYDERGHPLVQYHHPELANTRYRQSYIEHNLAHRRERELVCMYWEYGRDTWETIVEHKFVHIFWAGSDDCLTCGACVSQSTMNSIIPYLWPTFPIHANEPMTLAM"
           "VIMGKESPGTLFEDGGEQRYIVKEFWIPHLCQPINKDPGSLPGCDFASQYRVDTTTVSNPGDIENWYWEYAWTDKHPQFIWRIWCEHGFREESEYFVMQWLDMCESN"
           "QEMERPCEYEWLPETKDPSKYILNCPVNRQGPIRSKMEEIKQMRCIQVEGHAVSCESIMCVMIRQQEHMMSVKANDWIRPICRDMEEKKHDFFQTPQYDKMVAQFLW"
           "PQYVTRMD")
    print(function(p_1, p_2))
